- name: Install K3S on the master node
  hosts: k3s_master
  tasks:
    - name: Install K3S using the official install script to properly pre-configure the service for the master node
      shell: curl -sfL https://get.k3s.io | sh -
    - name: Get the node token and register it
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ k3s_token['content'] }}"
- name: Install K3S on the worker nodes
  hosts: k3s_nodes
  tasks:
    - name: Install K3S using the official install script to properly pre-configure the service for worker nodes
      shell: curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars[groups['k3s_master'][0]]['ansible_default_ipv4']['address'] }}:6443" K3S_TOKEN="{{ node-token['content'] }}" sh -
- name: Check K3S service and get cluster status
  hosts: k3s_master
  tasks:
    - name: Run kubectl status command to check that nodes joined correctly
      shell: kubectl get nodes
      register: k3s_cluster
    - name: Print returned information
      ansible.builtin.debug:
        msg: "{{ k3s_cluster }}"
    - name: Install the portainer agent on the master node for management
      shell: kubectl apply -f https://downloads.portainer.io/ce2-18/portainer-agent-k8s-nodeport.yaml