- name: Check if Swarm has already been Initialized
  community.docker.docker_node_info:
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_facts.default_ipv4.address }}"
  when: swarm_status.failed or swarm_status.nodes | length == 0
  run_once: true
  tags: swarm

- name: Get the Manager join-token
  ansible.builtin.command: docker swarm join-token --quiet manager
  register: manager_token
  changed_when: false
  when: not swarm_status.failed
  run_once: true
  tags: swarm

- name: Get the worker join-token
  ansible.builtin.command: docker swarm join-token --quiet worker
  register: worker_token
  changed_when: false
  when: not swarm_status.failed
  run_once: true
  tags: swarm
