- name: Add Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install the latest version of Docker Engine and containerd
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    update_cache: true
- name: Add the admin user to the docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
- name: Install Docker Module for Python and JSONdiff
  ansible.builtin.pip:
    name:
      - docker
      - jsondiff
      - pyyaml
      - docker-compose
- name: Start and enable Docker systemd service.
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
