- name: Download OpenBytes GPG key
  ansible.builtin.get_url:
    url: https://repo.openbytes.ie/openbytes.gpg
    dest: /usr/share/keyrings/openbytes.gpg
    mode: '0644'
- name: Add Patchman repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/patchman.list
    content: "deb [signed-by=/usr/share/keyrings/openbytes.gpg] https://repo.openbytes.ie/patchman/debian bookworm main"
    mode: '0644'
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes
- name: Install Patchman Client
  ansible.builtin.apt:
    name: patchman-client
    state: present
- name: Update Patchman Client configuration
  ansible.builtin.replace:
    path: /etc/patchman/patchman-client.conf
    regexp: 'https://patchman.example.com'
    replace: 'http://192.168.10.151/patchman/'
- name: Create cronjob for Patchman Client
  ansible.builtin.cron:
    name: "Run Patchman Client daily"
    minute: "0"
    hour: "1"
    job: "/usr/sbin/patchman-client"
- name: Run Patchman Client
  ansible.builtin.command: /usr/sbin/patchman-client