##### TERRAFORM VM DEPLOYMENT TO HYPERVISORS
- name: Deploy Application-Server Virtual-Machines on Proxmox with Terraform
  hosts: localhost
  gather_facts: false
  roles:
    - terraform-prepare
    - terraform-apply
  vars:
    vm_stack: app-servers
    project_dir: /home/abeckett/terraform/proxmox/app-servers

##### FIRST BOOT AND PAUSE FOR UPDATES
- name: Start vm-app-server-01
  hosts: hypervisor_01
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: vm-app-server-01

- name: Start vm-app-server-02
  hosts: hypervisor_01
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: vm-app-server-02