##### INITIAL CONFIGURATION
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: app_server_virtual_machines
  roles:
    - reboot
    - base-packages
    - disable-motd-ubuntu
    - qemu-guest-agent-install
    - webmin-install
    - snmp-configure
    - network-share-mount

##### PRE-SERVICE-CONFIGURATION SNAPSHOTS
- name: Take snapshot of vm-app-server-01
  hosts: hypervisor-01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Pre-service-configuration

- name: Take snapshot of vm-app-server-02
  hosts: hypervisor-01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Pre-service-configuration