- hosts: "*"
  become: true
  tasks:
    - name: Install qemu guest agent
      yum:
        name: qemu-guest-agent
        state: present
    - name: Start guest agent
      systemd:
        name: qemu-guest-agent
        state: started
        enabled: yes
