- hosts: "*"
  become: yes
  tasks:
    - name: Upgrade all packages and install kernel updates
      yum:
        update_cache: yes
        name: '*'
        state: latest
        
    - name: Check if system needs a reboot
      command: needs-restarting -r
      register: reboot_required
      failed_when: reboot_required.rc not in [0,1]

    - name: restart_server
      reboot:
      when: reboot_required.rc == 1 and do_reboot is defined