- hosts: "*"
  become: true
  tasks:
    - name: Upgrade all packages and install kernel updates
      yum:
        update_cache: yes
        update_only: yes
        name: '*'
        state: latest
      register: yum_update_status
    - name: Remove packates not needed anymore
      yum:
        autoremove: yes
    - name: List updated packages
      shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
      register: result
      args:
        warn: no
    - name: Updates packages
      debug: msg="{{ result.stdout_lines }}"
    - name: Reboot when packages were updated
      reboot:
      when: yum_update_status.changed