##### REMOVE TERRAFORM VM DEPLOYMENT FROM HYPERVISORS
- name: Destroy current Terraform Docker Server deployment on Proxmox
  hosts: localhost
  gather_facts: false
  roles:
    - terraform-destroy
  vars:
    project_dir: /home/terraform/proxmox/docker-servers/
