##### INITIAL CONFIGURATION
- name: Reboot machines, install updates and standard packages, configure SNMP and network shares
  hosts: docker_virtual_machines
  roles: 
    - reboot
    - base-packages
    - disable-motd-ubuntu
    - qemu-guest-agent-install
    - webmin-install
    - snmp-configure
    - network-share-mount
  vars:
    user: abeckett

##### PRE-SERVICE-CONFIGURATION SNAPSHOTS
- name: Take pre-service-configuration snapshot of VM-DOCKER-PROXY
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 101
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-DOCKER-MANAGEMENT
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 102
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-DOCKER-MEDIA
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 103
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-DOCKER-SERVICES
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 104
    snapshot_name: Pre-service-configuration

##### SERVICE INSTALL
- name: Install GlusterFS and Docker
  hosts: docker_virtual_machines
  roles: 
    - glusterfs-service
    - docker-install
  vars:
    user: abeckett

##### SERVICE-SPECIFIC CONFIGURATIONS
- name: Configure GlusterFS and start the service
  hosts: docker_proxy
  roles:
    - glusterfs-configure
  vars:
    nodes:
      - VM-DOCKER-MANAGEMENT.hyvecloud.internal
      - VM-DOCKER-MEDIA.hyvecloud.internal
      - VM-DOCKER-SERVICES.hyvecloud.internal
    replicas: 4
    cluster:
      - VM-DOCKER-PROXY.hyvecloud.internal
      - VM-DOCKER-MANAGEMENT.hyvecloud.internal
      - VM-DOCKER-MEDIA.hyvecloud.internal
      - VM-DOCKER-SERVICES.hyvecloud.internal

- name: Deploy Portainer to Management node
  hosts: docker_management
  roles: 
    - docker-portainer-deploy
  vars:
    user: abeckett

- name: Deploy Portainer-agent to other Docker servers
  hosts: docker_proxy,docker_media,docker_services
  roles: 
    - docker-portainer-agent-deploy

##### REBOOT AND POST-CONFIGURATION SNAPSHOTS
- name: Reboot Virtual Machines
  hosts: docker_virtual_machines
  roles: 
    - reboot

- name: Take post-configuration snapshot of VM-DOCKER-PROXY
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 101
    snapshot_name: Post-configuration

- name: Take post-configuration snapshot of VM-DOCKER-MANAGEMENT
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 102
    snapshot_name: Post-configuration

- name: Take post-configuration snapshot of VM-DOCKER-MEDIA
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 103
    snapshot_name: Post-configuration

- name: Take post-configuration snapshot of VM-DOCKER-SERVICES
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 104
    snapshot_name: Post-configuration
