##### REMOVE TERRAFORM VM DEPLOYMENT FROM HYPERVISORS
- name: Destroy current Terraform Docker Server deployment on Proxmox
  hosts: terraform
  roles:
    - terraform-destroy
  vars:
    project_dir: /Terraform/proxmox/docker-servers/
