- name: Deploy Docker Virtual-Machines on Proxmox with Terraform
  hosts: localhost
  roles:
    - terraform-prepare
    - terraform-apply
  vars:
    vm_stack: docker-servers
    project_dir: /home/abeckett/terraform/proxmox/docker-servers
    parallelism: 1
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: docker_vms
  roles: 
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
    - glusterfs-service
    - docker-install
- name: Configure GlusterFS and start the service
  hosts: docker_proxy
  roles:
    - glusterfs-configure
  vars:
    nodes:
      - VM-DOCKER-MEDIA.homelab.internal
      - VM-DOCKER-SERVICES.homelab.internal
      - VM-DOCKER-MANAGEMENT.homelab.internal
    replicas: 4
    cluster:
      - VM-DOCKER-PROXY.homelab.internal
      - VM-DOCKER-MEDIA.homelab.internal
      - VM-DOCKER-SERVICES.homelab.internal
      - VM-DOCKER-MANAGEMENT.homelab.internal
- name: Mount glusterfs share to VMs
  hosts: docker_vms
  roles: 
    - glusterfs-mount
- name: Deploy Portainer to Proxy node
  hosts: docker_proxy
  roles: 
    - container-directories
    - docker-container-deploy
  vars:
    service: portainer
- name: Deploy Portainer-agent to other Docker servers
  hosts: docker_media,docker_services,docker_management
  roles: 
    - docker-portainer-agent-deploy
- name: Reboot Virtual Machines
  hosts: docker_vms
  roles: 
    - reboot
- name: Take snapshot of VM-DOCKER-PROXY
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 200
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-MEDIA
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-SERVICES
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-MANAGEMENT
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Post-configuration
