##### TERRAFORM VM DEPLOYMENT TO HYPERVISORS
- name: Deploy Docker Virtual-Machines on Proxmox with Terraform
  hosts: localhost
  gather_facts: false
  roles:
    - terraform-prepare
    - terraform-apply
  vars:
    vm_stack: docker-servers
    project_dir: /home/terraform/proxmox/docker-servers/
    parallelism: 1

##### FIRST BOOT AND PAUSE FOR UPDATES
- name: Start VM-DOCKER-PROXY
  hosts: HYPERVISOR-01.hyvecloud.local
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: VM-DOCKER-SERVER-01

- name: Start VM-DOCKER-MEDIA
  hosts: HYPERVISOR-01.hyvecloud.local
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: VM-DOCKER-SERVER-02

- name: Start VM-DOCKER-SERVICES
  hosts: HYPERVISOR-01.hyvecloud.local
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: VM-DOCKER-SERVER-03

- name: Start VM-DOCKER-MANAGEMENT
  hosts: HYPERVISOR-01.hyvecloud.local
  roles:
    - proxmox-vm-start
  vars:
    proxmox_node: HYPERVISOR-01
    vm_name: VM-DOCKER-SERVER-04