- name: Deploy Docker Swarm Virtual-Machines on Proxmox with Terraform
  hosts: terraform
  roles:
    - terraform-apply
  vars:
    project_dir: /home/abeckett/terraform/proxmox/docker-swarm
    parallelism: 1
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: swarm_vms,lb
  roles: 
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
    - glusterfs-service
    - docker-install
- name: Configure GlusterFS and start the service
  hosts: swarm_manager
  roles:
    - glusterfs-configure
    - docker-swarm-init
  vars:
    nodes:
      - VM-SWARM-02.homelab.internal
      - VM-SWARM-03.homelab.internal
      - VM-LB-01.homelab.internal
    replicas: 4
    cluster:
      - VM-SWARM-01.homelab.internal
      - VM-SWARM-02.homelab.internal
      - VM-SWARM-03.homelab.internal
      - VM-LB-01.homelab.internal
- name: Mount glusterfs share to VMs
  hosts: swarm_vms,lb
  roles: 
    - glusterfs-mount
- name: Join the other nodes to Docker Swarm
  hosts: swarm_workers
  roles: 
    - docker-swarm-join
- name: Deploy Portainer to Swarm as a service
  hosts: swarm_manager
  roles: 
    - docker-container-deploy
  vars:
    service: portainer
- name: Deploy Portainer to Swarm as a service
  hosts: lb
  roles: 
    - loadbalancer-deploy
    - docker-portainer-agent-deploy
- name: Reboot Virtual Machines
  hosts: swarm_vms,lb
  roles: 
    - reboot
- name: Take snapshot of VM-SWARM-01
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 200
    snapshot_name: Post-configuration
- name: Take snapshot of VM-SWARM-01
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Post-configuration
- name: Take snapshot of VM-SWARM-02
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Post-configuration
- name: Take snapshot of VM-SWARM-03
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Post-configuration
