- name: Deploy Docker Virtual-Machines on Proxmox with Terraform
  hosts: localhost
  roles:
    - terraform-prepare
    - terraform-apply
  vars:
    vm_stack: docker-servers
    project_dir: /home/abeckett/terraform/proxmox/docker-servers
    parallelism: 1
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: docker_vms
  roles: 
    - reboot
    - update
    - base-packages
    - disable-motd-ubuntu
    - qemu-guest-agent-install
    - cockpit-install
    - snmp-configure
    - network-share-mount
    - glusterfs-service
    - docker-install
- name: Configure GlusterFS and start the service
  hosts: docker_management
  roles:
    - glusterfs-configure
  vars:
    nodes:
      - VM-DOCKER-MEDIA.hyvecloud.local
      - VM-DOCKER-SERVICES.hyvecloud.local
      - VM-DOCKER-PROXY.hyvecloud.local
    replicas: 4
    cluster:
      - VM-DOCKER-PROXY.hyvecloud.local
      - VM-DOCKER-MEDIA.hyvecloud.local
      - VM-DOCKER-SERVICES.hyvecloud.local
      - VM-DOCKER-MANAGEMENT.hyvecloud.local
- name: Mount glusterfs share to VMs
  hosts: docker_vms
  roles: 
    - glusterfs-mount
- name: Deploy Portainer to Proxy node
  hosts: docker_management
  roles: 
    - docker-portainer-deploy
  vars:
    service: portainer
- name: Deploy Portainer-agent to other Docker servers
  hosts: docker_media,docker_services,docker_proxy
  roles: 
    - docker-portainer-agent-deploy
- name: Reboot Virtual Machines
  hosts: docker_vms
  roles: 
    - reboot
- name: Take snapshot of VM-DOCKER-PROXY
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 100
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-MEDIA
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 101
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-SERVICES
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 102
    snapshot_name: Post-configuration
- name: Take snapshot of VM-DOCKER-MANAGEMENT
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 103
    snapshot_name: Post-configuration
