- hosts: swarm_manager
  become: true
  tasks:
    - name: Spin-up a Portainer 
      docker_container:
        name: Portainer
        image: portainer/portainer-ce
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9000:9000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
    - name: Initialize Docker Swarm
      docker_swarm:
        state: present
      run_once: true
    - name: Get the worker join-token
      docker_swarm_info:
        nodes: yes
      register: result
    - debug:
        var: result.swarm_facts

- hosts: swarm_nodes
  become: true
  tasks:
    - name: Add Workers to the Swarm
      community.docker.docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ hostvars['swarm-manager']['worker_token']['stdout'] }}"
        remote_addrs: [ '192.168.1.163:2377' ]