- hosts: "*"
  become: true
  tasks:
    - name: Install required system packages [Debian/Ubuntu]
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install required system packages [CentOS/Rocky]
      dnf:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
        when:
          - ansible_facts.os_family == "RedHat"
    - name: Add Docker GPG Key [Debian/Ubuntu]
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Add Docker Repository [Debian/Ubuntu]
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu/dists/focal/stable/
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Add Docker Repository [CentOS/Rocky]
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: no
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Install the latest version of Docker Engine and containerd [Debian/Ubuntu]
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install the latest version of Docker Engine and containerd [CentOS/Rocky]
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Add the admin user to the docker group
      user:
        name: abeckett
        groups: docker
        append: yes
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Start and enable Docker systemd service.
      systemd:
        name: docker
        state: started
        enabled: true
        daemon_reload: true