##### TERRAFORM VM DEPLOYMENT TO HYPERVISORS
- name: Deploy Docker Virtual-Machines on Proxmox with Terraform
  hosts: localhost
  gather_facts: false
  roles:
    - terraform-prepare
    - terraform-apply
  vars:
    vm_stack: docker-servers
    project_dir: /Terraform/proxmox/docker-servers/
    parallelism: 2
