- hosts: loadbalancer
  become: true
  tasks:
    - name: Check if Swarm has already been Initialized
      shell: docker node ls
      register: swarm_status
      ignore_errors: true
    - name: Initialize Docker Swarm
      docker_swarm:
        state: present
      when: swarm_status.rc != 0
      run_once: true   
    - name: Deploy NGINX load-balancer
      community.docker.docker_container:
        name: Load-Balancer
        image: nginx
        state: started
        volumes:
          - /nas-01/Container-configs/loadbalancer/:/etc/nginx/conf.d
        ports:
        - 9003:9003
        - 9004:9004
        - 9005:9005
        - 9006:9006
        - 9007:9007
        - 9008:9008
        - 9009:9009
        - 9010:9010
        - 9011:9011
        - 9012:9012
        - 10000:10000
        - 10001:10001
        - 10002:10002
        - 10003:10003
        - 10004:10004
        - 10005:10005
        - 10006:10006
        - 10007:10007
        - 10008:10008
        - 10009:10009
        - 10010:10010
        - 10011:10011
        - 10012:10012
        - 11000:11000
        - 11001:11001
        - 11002:11002
        - 11003:11003
        - 11004:11004
        - 11005:11005
        - 11006:11006
        - 11007:11007
        - 11008:11008
        - 11009:11009
        - 11010:11010
        - 11011:11011
        - 11012:11012
        restart_policy: always



        