- name: Install updates and standard packages, configure SNMP and network shares
  hosts: game_servers
  roles:
    - update
    - base-packages
  vars:
    user: abeckett

- name: Install Pelican Panel (Game Server Management Interface)
  hosts: game_server_panel
  become: yes
  vars:
    reverse_proxy_ip: "{{ lookup('env', 'REVERSE_PROXY_IP') }}"
  roles:
    - install-pelican-panel

- name: Install Pelican Wings (Game Server Daemon)
  hosts: game_server_nodes
  become: yes
  roles:
    - install-pelican-wings
