- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-GAMESERVER-01
    vm_id: 208
    tags: docker,pufferpanel,app-server
    cores: 8
    memory: 16384
    ip_address: gw=192.168.0.1,ip=192.168.0.168/24
    disk_size: 100G
- hosts: virtual_machines
  roles:
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
- hosts: game_server
  roles:
    - docker-install
    - pufferpanel-install
- hosts: virtual_machines
  roles: 
    - reboot
- hosts: proxmox_servers
  roles:
    - post-config-snapshot