##### INITIAL CONFIGURATION
- name: Install updates and standard packages, configure SNMP and network shares
  hosts: game_servers
  roles: 
    - update
    - base-packages
    - disable-motd-ubuntu
    - webmin-install
    - snmp-configure
  vars:
    user: abeckett
