- hosts: "glusterfs_servers"
  become: true
  tasks:
    - name: Install software-properties-common [Debian/Ubuntu]
      apt:
        name:
        - software-properties-common
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install GlusterFS [Debian/Ubuntu]
      apt:
        name:
        - glusterfs-server
        - glusterfs-client
        state: present
        update_cache: yes
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install GlusterFS [CentOS/Rocky]
      dnf:
        name: 
        - glusterfs-server
        - glusterfs-client
        state: present
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Start glusterd service
      systemd:
        name: glusterd
        enabled: yes
        state: started
    - name: Create GlusterFS brick-1 directory
      ansible.builtin.file:
        path: /glusterfs/bricks/gv0
        state: directory
    - name: Create List of nodes to be added to the Trusted Storage Pool
      set_fact: storagepoolnodelist={%for host in groups['glusterfs_connected_nodes']%}"{{hostvars[host].ansible_eth0.ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}
    - name: Create List of nodes to be added to the Cluster
      set_fact: clusternodelist={%for host in groups['glusterfs_servers']%}"{{hostvars[host].ansible_eth0.ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}  
- hosts: "glusterfs_primary_node"
  become: true
  tasks:
    - name: Create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - "{{ storagepoolnodelist }}"
    - name: Create GlusterFS volume
      gluster.gluster.gluster_volume:
        state: present
        name: gv0
        replicas: 4                                                                           # Change this depending on the number of servers in the cluster
        bricks: /glusterfs/bricks/gv0
        cluster:
          - "{{ clusternodelist }}"
        force: true
      run_once: true
    - name: Start GlusterFS volume
      gluster.gluster.gluster_volume:
        state: started
        name: gv0
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:/gv0"
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted
- hosts: "glusterfs_connected_nodes"
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:/gv0"
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted