- hosts: loadbalancer
  become: true
  tasks:
    - name: Create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - 192.168.0.161
          - 192.168.0.162
          - 192.168.0.163
    - name: Create GlusterFS volume
      gluster.gluster.gluster_volume:
        state: present
        name: gv0
        replicas: 4
        bricks: /glusterfs/bricks/gv0
        cluster:
          - 192.168.0.160
          - 192.168.0.161
          - 192.168.0.162
          - 192.168.0.163
        force: true
      run_once: true
    - name: Start GlusterFS volume
      gluster.gluster.gluster_volume:
        state: started
        name: gv0
- hosts: loadbalancer
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: VM-LB-01.homelab.internal:/gv0
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted
- hosts: swarm_manager
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: VM-SWARM-03.homelab.internal:/gv0
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted
- hosts: swarm_1
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: VM-SWARM-01.homelab.internal:/gv0
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted
- hosts: swarm_2
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: VM-SWARM-02.homelab.internal:/gv0
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted