- name: Deploy Kubernetes Cluster Virtual-Machines on Proxmox with Terraform
  hosts: terraform
  roles:
    - terraform-apply
  vars:
    project_dir: /home/abeckett/terraform/proxmox/kubernetes-cluster
    parallelism: 1
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: kubernetes_vms
  roles: 
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
  vars:
    SNMP_comunity: HyveCloudHomelab
- name: Reboot Virtual Machines
- hosts: kubernetes_vms
  roles: 
    - reboot
- name: Take snapshot of VM-K3S-01
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 211
    snapshot_name: Post-configuration
- name: Take snapshot of VM-K3S-02
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 212
    snapshot_name: Post-configuration
- name: Take snapshot of VM-K3S-03
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 213
    snapshot_name: Post-configuration