- name: Deploy Kubernetes Cluster Virtual-Machines on Proxmox with Terraform
  hosts: terraform
  roles:
    - terraform-apply
  vars:
    project_dir: /home/abeckett/terraform/proxmox/kubernetes-cluster
    parallelism: 1
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: kubernetes_vms
  roles: 
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
    - k3s-prerequisites
  vars:
    SNMP_comunity: HyveCloudHomelab
    k3s_version: v1.22.3+k3s1
- name: Deploy K3s to master node
  hosts: k3s_master
  roles:
    - k3s-master-deploy
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
    ansible_user: abeckett
- name: Deploy K3s to worker nodes
  hosts: k3s_nodes
  roles:
    - k3s-node-deploy
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
- name: Deploy Portainer Agent to cluster
  hosts: k3s_master
  roles:
    - kubernetes-portainer-agent-deploy
- name: Reboot Virtual Machines
  hosts: kubernetes_vms
  roles: 
    - reboot
- name: Take snapshot of VM-K3S-01
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 211
    snapshot_name: Post-configuration
- name: Take snapshot of VM-K3S-02
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 212
    snapshot_name: Post-configuration
- name: Take snapshot of VM-K3S-03
  hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 213
    snapshot_name: Post-configuration