##### INITIAL CONFIGURATION
- name: Reboot machines, install updates and base packages, configure SNMP and network shares
  hosts: kubernetes_virtual_machines
  roles: 
    - reboot
    - base-packages
    - disable-motd-ubuntu
    - qemu-guest-agent-install
    - cockpit-install
    - snmp-configure
    - network-share-mount
    - k3s-prerequisites
  vars:
    k3s_version: v1.27.10+k3s2
    user: abeckett

##### PRE-SERVICE-CONFIGURATION SNAPSHOTS
- name: Take pre-service-configuration snapshot of VM-K3S-SERVER-01
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-K3S-SERVER-02
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-K3S-SERVER-03
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-K3S-SERVER-04
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 204
    snapshot_name: Pre-service-configuration

- name: Take pre-service-configuration snapshot of VM-K3S-SERVER-05
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 205
    snapshot_name: Pre-service-configuration

##### K3S INSTALL AND DEPLOYMENT
- name: Deploy K3s to master node
  hosts: vm_k3s_server_01
  roles:
    - k3s-master-deploy
  vars:
    master_ip: 192.168.0.171
    ansible_user: abeckett

- name: Deploy K3s to worker nodes
  hosts: vm_k3s_server_02,vm_k3s_server_03,vm_k3s_server_04,vm_k3s_server_05
  roles:
    - k3s-node-deploy
  vars:
    master_ip: 192.168.0.171

- name: Reboot Virtual Machines
  hosts: kubernetes_virtual_machines
  roles: 
    - reboot

- name: Deploy Portainer Agent to cluster
  hosts: vm_k3s_server_01
  roles:
    - kubernetes-portainer-agent-deploy
    - rancher-install

##### PRE-SERVICE-CONFIGURATION SNAPSHOTS
- name: Take post-service-configuration snapshot of VM-K3S-SERVER-01
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Post-service-configuration

- name: Take post-service-configuration snapshot of VM-K3S-SERVER-02
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Post-service-configuration

- name: Take post-service-configuration snapshot of VM-K3S-SERVER-03
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Post-service-configuration

- name: Take post-service-configuration snapshot of VM-K3S-SERVER-04
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 204
    snapshot_name: Post-service-configuration

- name: Take post-service-configuration snapshot of VM-K3S-SERVER-05
  hosts: hypervisor_01
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 205
    snapshot_name: Post-service-configuration