- name: Playbook for configuration of SNMP on linux based hosts
  hosts: "*"
  become: true
  tasks:
    - name: Update cache & install SNMP packages [Debian/Ubuntu]
      apt:
        name:
          - net-snmp
          - net-snmp-utils
        state: latest
        update_cache: yes
      when:
        - ansible_facts.os_family == "Debian"
    - name: Update cache & install SNMP packages [CentOS/Rocky]
      dnf:
        name:
          - net-snmp
          - net-snmp-utils
        state: latest
        update_cache: yes
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Configure SNMP server
      copy: src=/home/abeckett/snmpd.conf dest=/etc/snmp/snmpd.conf owner=root group=root mode=600
    - name: Start and enable SNMPd systemd service.
      systemd:
        name: snmpd
        state: started
        enabled: true
        daemon_reload: true

