- hosts: "*"
  become: true
  tasks:
    - name: Reboot systems
      reboot:
        post_reboot_delay: 60
        test_command: uptime
    - name: Send Mattermost alert on completion
      community.general.mattermost:
        url: https://mattermost.beckettcloud.com
        api_key: 3wyfzahfcfn6uy6cm5s9kxjh4e
        text: '{{ inventory_hostname }} OS updates completed'
