- name: Playbook for configuration of SNMP on linux based hosts
  hosts: "*"
  become: true
  tasks:
    - name: Update cache & install SNMP packages [Debian/Ubuntu]
      apt:
        name:
          - snmpd
          - snmp
          - libsnmp-dev
          - python3-setuptools
          - python3-pip
        state: latest
        update_cache: yes
      when:
        - ansible_facts.os_family == "Debian"
    - name: Update cache & install SNMP packages [CentOS/Rocky]
      dnf:
        name:
          - net-snmp
          - net-snmp-utils
          - python3-setuptools
          - python3-pip
        state: latest
        update_cache: yes
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Install Docker Module for Python
      pip:
        name: pysnmp
    - name: Configure SNMP server
      copy: src=/home/abeckett/snmpd.conf dest=/etc/snmp/snmpd.conf owner=root group=root mode=600
    - name: Start and enable SNMPd systemd service.
      systemd:
        name: snmpd
        state: started
        enabled: true
        daemon_reload: true
    - name: Restart SNMPd systemd service if already running.
      systemd:
        name: snmpd
        state: restarted
    - name: Test that SNMP is working
      community.general.snmp_facts:
        host: '{{ inventory_hostname }}'
        version: v2c
        community: BCloudHomelab
      register: response
    - name: Print the results of the test
      debug:
        var: response

