- name: Update packages on LXC containers
  hosts: lxc_containers
  roles:
    - update
    - reboot-required-check
  vars:
    update_report_discord_webhook_url: "{{ lookup('env', 'VMS_LXCS_UPDATE_REPORT_DISCORD_WEBHOOK_URL') }}"
