##### INITIAL CONFIGURATION
- name: Reboot machines, install updates and standard packages, configure SNMP and network shares
  hosts: lxc_containers
  roles: 
    - reboot
    - update
    - base-packages
    - disable-motd-ubuntu
    - cockpit-install
    - snmp-configure