- name: Reboot machines, install updates and standard packages, configure SNMP and network shares
  hosts: docker_virtual_machines
  roles:
    - reboot
    - base-packages
    - docker-install
  vars:
    user: abeckett
