- name: Install base packages, disable MOTD, install Docker and Hawser agent
  hosts: docker_vms
  roles:
    - base-packages
    - linux-disable-motd
    - docker-install
    - dockhand-hawser-agent-install
  vars:
    user: abeckett
