- name: Rolling reboot of Proxmox HA cluster
  hosts: pve_test_cluster_01
  serial: 1
  become: yes
  vars:
    vms_on_node: []
  pre_tasks:
    
  roles:
    - proxmox-check-vms
    - proxmox-migration-check-vms-initial
    - proxmox-node-reboot
    - proxmox-migration-check-vms-returned

- name: Gather VM/LXC info for reporting and send final report in Discord
  hosts: pve_test_cluster_01
  gather_facts: no
  become: yes
  vars:
    reboot_report_discord_webhook_url: "{{ lookup('env', 'REBOOT_REPORT_DISCORD_WEBHOOK_URL') }}"
  roles:
    - proxmox-cluster-reboot-report