- hosts: "*"
  become: true
  tasks:
    - name: Create virtual-machine with specific hardware requirements
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        tags: "{{ tags }}"
        ostype: l26
        cpu: kvm64
        sockets: 2
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        agent: 'enabled=1'
        scsihw: virtio-scsi-pci
        scsi:
          scsi0: "{{ storage }}"
        ide:
          ide0: "{{ iso }}"
        net:
          net0: 'virtio,bridge=vmbr0,firewall=1'
        timeout: 90
    - name: Start virtual-machine
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        state: started
