- hosts: proxmox_servers
  become: true
  tasks:
    - name: Clone virtual-machine from template
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        clone: template
        vmid: "{{ template_id }}"
        name: "{{ vm_name }}"
        storage: pool-1
        format: raw
        timeout: 300
    - name: Edit new virtual-machine with new cloud-init parameters
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        tags: "{{ tags }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        citype: nocloud
        ciuser: "{{ username }}"
        cipassword: "{{ password }}"
        sshkeys: "{{ sshkeys }}"
        searchdomains: 'homelab.internal'
        nameservers: 192.168.0.210,192.168.0.1
        ipconfig: 
          ipconfig0: "{{ ip_address }}"
        update: true
    - name: Re-size virtual-machine disk
      community.general.proxmox_disk:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        disk: scsi0
        size: "{{ disk_size }}"
        state: resized
    - name: Start virtual-machine
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        state: started
    - name: Pause for 30 seconds while virtual-machine boots
      ansible.builtin.pause:
        seconds: 30

- hosts: ubuntu_test_hosts
  become: true
  tasks:
    - name: Preliminary checks
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: Install all updates
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: Install required base-packages (qemu-guest-agent, cockpit, cifs-utils)
      apt:
        name:
        - qemu-guest-agent
        - cockpit
        - cifs-utils
        - keyutils
        state: present
    - name: Install cockpit navigator plugin
      apt:
        deb: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        state: present
    - name: Install cockpit file sharing plugin
      apt:
        deb: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.2/cockpit-file-sharing_3.3.2-1focal_all.deb
        state: present
    - name: Start qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    - name: Start cockpit service
      systemd:
        name: cockpit
        enabled: yes
        state: started
        masked: no
    - name: Create NAS-01 local directory
      ansible.builtin.file:
        path: /nas-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett
    - name: Mount NAS-01 network share
      ansible.posix.mount:
        src: //NAS-01.homelab.internal/Media
        path: /nas-01
        fstype: cifs
        opts: "{{ nas_01_auth }}"
        state: mounted
    - name: Create STORAGE-01 local directory
      ansible.builtin.file:
        path: /storage-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett
    - name: Mount STORAGE-01 network share
      ansible.posix.mount:
        src: //STORAGE-01.homelab.internal/Media
        path: /storage-01
        fstype: cifs
        opts: "{{ storage_01_auth }}"
        state: mounted