- hosts: "*"
  become: true
  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: update cache
      apt:
        update_cache: yes
    - name: install all updates
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: result
    - name: List installed and updated packages
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
    - name: Show Output
      debug: msg="{{ result.stdout_lines }}"
    - name: Send Mattermost alert on completion
      community.general.mattermost:
        url: https://mattermost.beckettcloud.com
        api_key: 3wyfzahfcfn6uy6cm5s9kxjh4e
        text: '{{ inventory_hostname }} OS updates completed'
