- hosts: proxmox_servers
  become: true
  tasks:
    - name: Preliminary checks
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: Install all updates and auto-remove old/unused packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: Check if a reboot is required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the Debian or Ubuntu server
      debug:
        msg: "Reboot is required on {{ inventory_hostname }}"
      when: reboot_required_file.stat.exists
