- hosts: proxmox_servers
  become: true
  tasks:
    - name: Clone virtual-machine from template
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        clone: template
        vmid: "{{ template_id }}"
        name: "{{ vm_name }}"
        newid: "{{ vm_id }}"
        storage: pool-1
        format: raw
        timeout: 300
    - name: Edit new virtual-machine with new cloud-init parameters
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        tags: "{{ tags }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        citype: nocloud
        ciuser: "{{ username }}"
        cipassword: "{{ password }}"
        sshkeys: "{{ sshkeys }}"
        searchdomains: 'homelab.internal'
        nameservers: 192.168.0.210,192.168.0.1
        ipconfig: 
          ipconfig0: "{{ ip_address }}"
        update: true
    - name: Re-size virtual-machine disk
      community.general.proxmox_disk:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        disk: scsi0
        size: "{{ disk_size }}"
        state: resized
    - name: Start virtual-machine
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        name: "{{ vm_name }}"
        state: started
    - name: Pause for 60 seconds while virtual-machine boots
      ansible.builtin.pause:
        seconds: 60

- hosts: docker_vms,app_vms
  become: true
  tasks:
    - name: Preliminary checks [Debian/Ubuntu]
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install all updates [Debian/Ubuntu]
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
      when:
        - ansible_facts.os_family == "Debian"
    - name: Upgrade all packages and install kernel updates [CentOS/Rocky]
      dnf:
        update_cache: yes
        update_only: yes
        name: '*'
        state: latest
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Remove packages not needed anymore [CentOS/Rocky]
      dnf:
        autoremove: yes
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Install required base-packages (qemu-guest-agent, cockpit, cifs-utils, nfs-common) [Debian/Ubuntu]
      apt:
        name:
        - qemu-guest-agent
        - cockpit
        - cifs-utils
        - nfs-common
        - keyutils
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install required base-packages (qemu-guest-agent, cifs-utils, nfs-common) [CentOS/Rocky]
      dnf:
        name: 
        - qemu-guest-agent
        - cifs-utils
        - nfs-common
        - keyutils
        - epel-release
        state: present
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Install cockpit navigator plugin [Debian/Ubuntu]
      apt:
        deb: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install cockpit navigator plugin [CentOS/Rocky]
      dnf:
        name: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.8/cockpit-navigator-0.5.8-2.el8.noarch.rpm
        state: present
        disable_gpg_check: True
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Install cockpit file sharing plugin [Debian/Ubuntu]
      apt:
        deb: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.2/cockpit-file-sharing_3.3.2-1focal_all.deb
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install cockpit file sharing plugin [CentOS/Rocky]
      dnf:
        name: https://github.com/45Drives/cockpit-file-sharing/releases/download/v2.4.5/cockpit-file-sharing-2.4.5-1.el8.noarch.rpm
        state: present
        disable_gpg_check: True
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Start qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    - name: Start cockpit service [Debian/Ubuntu]
      systemd:
        name: cockpit
        enabled: yes
        state: started
        masked: no
      when:
        - ansible_facts.os_family == "Debian"
    - name: Enable cockpit.socket [CentOS/Rocky]
      systemd:
        name: cockpit.socket
        enabled: yes
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Start cockpit [CentOS/Rocky]
      systemd:
        name: cockpit
        state: started
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Create NAS-01 local directory
      ansible.builtin.file:
        path: /nas-01
        state: directory
        mode: '0755'
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Mount NAS-01 network share
      ansible.posix.mount:
        src: NAS-01.homelab.internal:/volume1/Media
        path: /nas-01
        fstype: nfs
        boot: true
        opts: rw,sync,hard
        state: mounted
    - name: Create STORAGE-01 local directory
      ansible.builtin.file:
        path: /storage-01
        state: directory
        mode: '0755'
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Mount STORAGE-01 network share
      ansible.posix.mount:
        src: STORAGE-01.homelab.internal:/mnt/user/media
        path: /storage-01
        fstype: nfs
        boot: true
        opts: rw,sync,hard
        state: mounted
    - name: Create file with NetworkManager config to fix issue with NetworkManager and Cockpit [Debian/Ubuntu]
      copy:
        dest: /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
        content: |
          [keyfile]
          unmanaged-devices=none
      when:
        - ansible_facts.os_family == "Debian"
    - name: Create fake network interface to fix issue with NetworkManager and Cockpit [Debian/Ubuntu]
      ansible.builtin.command: nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24 gw4 1.2.3.1
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install extra packages [Debian/Ubuntu]
      apt:
        name:
        - neofetch
        state: present
      when:
        - ansible_facts.os_family == "Debian"
    - name: Install extra packages [CentOS/Rocky]
      dnf:
        name: 
        - neofetch
        state: present
      when:
        - ansible_facts.os_family == "RedHat"
    - name: Reboot systems
      reboot:
        post_reboot_delay: 60
        test_command: uptime
      when:
        - ansible_facts.os_family == "Debian" or ansible_facts.os_family == "RedHat"
