- name: Update packages on proxmox hypervisors
  hosts: cluster_01
  roles:
    - update
    - reboot-required-check
  vars:
    update_report_discord_webhook_url: "{{ lookup('env', 'PVE_CLUSTERS_UPDATE_REPORT_DISCORD_WEBHOOK_URL') }}"
