- hosts: proxmox_servers
  become: true
  tasks:
    - name: Preliminary checks
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: Install all updates and auto-remove old/unused packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
