- hosts: "*"
  become: true
  tasks:
    - name: Create virtual-machine with specific hardware requirements and configures cloud-init
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        # leave the above as default
        name: "{{ vm_name }}" # name shown in proxmox-gui
        tags: "{{ tags }}" # sets the tags for the virtual machine within proxmox for better identification
        ostype: l26 # LEAVE AS DEFAULT
        cpu: kvm64 # LEAVE AS DEFAULT
        sockets: 2 # number of cpu sockets, in most scenarios this will be set as 2
        cores: "{{ cores }}" # number of cpu cores
        memory: "{{ memory }}" # memory in megabytes. e.g. 4096 (4GB), 2048 (2GB), 8192 (8GB)
        agent: 'enabled=1' # enables qemu guest agent support
        scsihw: virtio-scsi-pci # defines the storage provider backend
        scsi:
          scsi0: "{{ storage }}" # creates the disk, the number after pool-1 defines the size of the disk in GB
        ide:
          ide0: "{{ iso }}" # attaches the install iso as boot media
          ide1: 'pool-1:cloudinit,format=raw' # attaches a cloud-init drive
        net: # defines the network configuration in proxmox for the virtual machine
          net0: 'virtio,bridge=vmbr0,firewall=1'
        citype: nocloud # default for linux, do not change
        ciuser: "{{ username }}" # virtual machine username
        cipassword: "{{ password }}" # virtual machine password
        searchdomains: 'homelab.internal'
        nameservers: 192.168.0.210,192.168.0.1
        ipconfig: # sets a static ip address within the virtual-machine with cloud-init
          ipconfig0: "{{ ip_address }}"

    - name: Start virtual-machine
      community.general.proxmox_kvm:
        node: phs-hv-01
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: phs-hv-01
        # leave above as default
        name: "{{ vm_name }}" # the name of the virtual machine
        state: started # starts the virtual machine
