- name: Rolling reboot of Proxmox HA cluster
  hosts: pve_test_cluster_01
  serial: 1
  become: yes
  vars:
    vms_on_node: []
    all_reports: []
  gather_facts: yes
  roles:
    - proxmox-migration-check-vms-initial
    - proxmox-node-reboot
    - proxmox-migration-check-vms-returned