- hosts: proxmox_servers
  roles:
    - virtual-machine-create
- hosts: virtual_machines
    - base-packages
    - snmp-configure
    - network-share-mount
- hosts: proxmox_servers
    - pre-config-snapshot
    - glusterfs-configure
    - docker-install
    - docker-swarm-deployment
    - gitlab-install
    - linux-reboot
    - post-config-snapshot