- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-LB-01
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-SWARM-01
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-SWARM-02
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-SWARM-03
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-GIT-01
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-K3S-01-MASTER
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-K3S-02-WORKER
- hosts: proxmox_servers
  roles:
    - proxmox-stop-virtual-machines
  vars:
    vm_name: VM-K3S-03-WORKER
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-LB-01
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-SWARM-01
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-SWARM-02
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-SWARM-03
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-GIT-01
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-K3S-01-MASTER
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-K3S-02-WORKER
- hosts: proxmox_servers
  roles:
    - proxmox-destroy-virtual-machines
  vars:
    vm_name: VM-K3S-03-WORKER