- hosts: proxmox_servers
  roles:
    - virtual-machine-create
- hosts: virtual_machines
  roles:
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
- hosts: swarm_vms
  roles:
    - glusterfs-service
- hosts: loadbalancer
  roles:
    - glusterfs-configure
- hosts: swarm_vms
  roles:
    - glusterfs-mount
    - docker-install
- hosts: swarm_manager
  roles:
    - docker-swarm-init
- hosts: swarm_nodes
  roles: 
    - docker-swarm-join
- hosts: loadbalancer
  roles: 
    - loadbalancer-configure
- hosts: swarm_manager
  roles: 
    - portainer-agent-deploy
- hosts: git
  roles: 
    - gitlab-install
- hosts: virtual_machines
  roles: 
    - reboot
- hosts: proxmox_servers
  roles:
    - post-config-snapshot