## INSTALL UPDATES, BASE PACKAGES, CONFIGURE SNMP AND MOUNT NETWORK SHARES
- hosts: terraform
  roles:
    - terraform-apply
  vars:
    project_dir: ~/terraform/proxmox

- hosts: virtual_machines
  roles:
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount

## VM-SWARM-01 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Post-update-early-configuration

## VM-SWARM-02 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Post-update-early-configuration

## VM-SWARM-03 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Post-update-early-configuration

## VM-SWARM-04 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 204
    snapshot_name: Post-update-early-configuration

## VM-SWARM-05 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 205
    snapshot_name: Post-update-early-configuration

## VM-GAMESERVER-01 PRE-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 206
    snapshot_name: Post-update-early-configuration

## INSTALL GLUSTERFS
- hosts: swarm_vms
  roles:
    - glusterfs-service

## CONFIGURE GLUSTERFS AND START FILESYSTEM
- hosts: swarm_manager
  roles:
    - glusterfs-configure
  vars:
    nodes:
      - VM-SWARM-02.homelab.internal
      - VM-SWARM-03.homelab.internal
      - VM-SWARM-04.homelab.internal
      - VM-SWARM-05.homelab.internal
    replicas: 5
    cluster:
      - VM-SWARM-01.homelab.internal
      - VM-SWARM-02.homelab.internal
      - VM-SWARM-03.homelab.internal
      - VM-SWARM-04.homelab.internal
      - VM-SWARM-05.homelab.internal

## MOUNT GLUSTER CLUSTER TO ALL NODES AND INSTALL DOCKER
- hosts: swarm_vms
  roles:
    - glusterfs-mount
    - docker-install

## INITIALIZE DOCKER SWARM
- hosts: swarm_manager
  roles:
    - docker-swarm-init

## JOIN NODES TO DOCKER SWARM
- hosts: swarm_workers
  roles: 
    - docker-swarm-join

## INSTALL TRAEFIK CONTAINER
- hosts: swarm_manager
  roles: 
    - docker-reverse-proxy-deploy

## INSTALL PORTAINER
- hosts: swarm_manager
  roles: 
    - docker-container-deploy
  vars:
    service: portainer

## INSTALL PUFFERPANEL AND DOCKER, CONFIGURE FOR INITIAL SETUP
- hosts: game_server
  roles:
    - docker-install
    - pufferpanel-install
    - portainer-agent-deploy

## REBOOT ALL VMs
- hosts: virtual_machines
  roles: 
    - reboot

## VM-SWARM-01 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 201
    snapshot_name: Post-configuration

## VM-SWARM-02 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 202
    snapshot_name: Post-configuration

## VM-SWARM-03 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 203
    snapshot_name: Post-configuration

## VM-SWARM-04 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 204
    snapshot_name: Post-configuration

## VM-SWARM-05 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 205
    snapshot_name: Post-configuration

## VM-GAMESERVER-01 POST-CONFIG SNAPSHOT
- hosts: proxmox_servers
  roles:
    - proxmox-snapshot
  vars:
    vm_id: 206
    snapshot_name: Post-configuration