- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-LB-01
    vm_id: 200
    tags: load-balancer,docker,glusterfs
    cores: 4
    memory: 4096
    ip_address: gw=192.168.0.1,ip=192.168.0.160/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-SWARM-01
    vm_id: 201
    tags: docker,app-server,glusterfs
    cores: 8
    memory: 8192
    ip_address: gw=192.168.0.1,ip=192.168.0.161/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-SWARM-02
    vm_id: 202
    tags: docker,app-server,glusterfs
    cores: 8
    memory: 8192
    ip_address: gw=192.168.0.1,ip=192.168.0.162/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-SWARM-03
    vm_id: 203
    tags: docker,app-server,glusterfs
    cores: 8
    memory: 8192
    ip_address: gw=192.168.0.1,ip=192.168.0.163/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-GIT-01
    vm_id: 204
    tags: gitlab,app-server
    cores: 8
    memory: 8192
    ip_address: gw=192.168.0.1,ip=192.168.0.164/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-K3S-01-MASTER
    vm_id: 205
    tags: kubernetes,app-server,master
    cores: 4
    memory: 4096
    ip_address: gw=192.168.0.1,ip=192.168.0.165/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-K3S-02-WORKER
    vm_id: 206
    tags: kubernetes,app-server,worker
    cores: 4
    memory: 4096
    ip_address: gw=192.168.0.1,ip=192.168.0.166/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-K3S-03-WORKER
    vm_id: 207
    tags: kubernetes,app-server,worker
    cores: 4
    memory: 4096
    ip_address: gw=192.168.0.1,ip=192.168.0.167/24
    disk_size: 200G
- hosts: proxmox_servers
  roles:
    - proxmox-create-from-clone
  vars:
    template_id: 1000
    vm_name: VM-GAMESERVER-01
    vm_id: 208
    tags: docker,pufferpanel,app-server
    cores: 8
    memory: 16384
    ip_address: gw=192.168.0.1,ip=192.168.0.168/24
    disk_size: 200G
- hosts: virtual_machines,game_server
  roles:
    - reboot
    - update
    - base-packages
    - snmp-configure
    - network-share-mount
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 200
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 201
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 202
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 203
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 204
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 205
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 206
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 207
- hosts: proxmox_servers
  roles:
    - pre-config-snapshot
  vars:
    vm_id: 208
- hosts: swarm_vms
  roles:
    - glusterfs-service
- hosts: loadbalancer
  roles:
    - glusterfs-configure
- hosts: swarm_vms
  roles:
    - glusterfs-mount
    - docker-install
- hosts: swarm_manager
  roles:
    - docker-swarm-init
- hosts: swarm_nodes
  roles: 
    - docker-swarm-join
- hosts: loadbalancer
  roles: 
    - loadbalancer-configure
- hosts: swarm_manager
  roles: 
    - portainer-agent-deploy
- hosts: git
  roles: 
    - gitlab-install
- hosts: game_server
  roles:
    - docker-install
    - pufferpanel-install
- hosts: virtual_machines,game_server
  roles: 
    - reboot
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 200
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 201
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 202
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 203
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 204
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 205
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 206
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 207
- hosts: proxmox_servers
  roles:
    - post-config-snapshot
  vars:
    vm_id: 208
