- hosts: "*"
  become: true
  tasks:
    - name: Reboot systems
      reboot:
        post_reboot_delay: 60
        test_command: uptime
      when:
        - ansible_facts.os_family == "Debian" or ansible_facts.os_family == "RedHat"
    - name: Reboot the machine with all defaults
      ansible.windows.win_reboot:
        post_reboot_delay: 60
        test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
      when:
        - ansible_facts.os_family == "Windows"
    - name: Send Mattermost alert on completion
      community.general.mattermost:
        url: https://mattermost.beckettcloud.com
        api_key: 3wyfzahfcfn6uy6cm5s9kxjh4e
        text: '{{ inventory_hostname }} - Server reboot completed'
