- hosts: swarm_manager
  become: true
  tasks:
    - name: Start portainer_agent service
      docker_swarm_service:
        name: portainer_agent
        image: portainer/agent:2.18.2
        networks:
          - portainer_agent_network
        publish:
          - published_port: 9001
            target_port: 9001
            protocol: tcp
        mode: global
        placement:
          constraints:
            - node.platform.os == linux
        mounts:
          - source: //var/run/docker.sock
            target: /var/run/docker.sock
            type: bind
          - source: //var/lib/docker/volumes
            target: /var/lib/docker/volumes
            type: bind