- hosts: "*"
  become: yes
  sudo: true
  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: update cache
      apt:
        update_cache: yes
    - name: install all updates
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: result
    - name: List installed and updated packages
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
    - name: Show Output
      debug: msg="{{ result.stdout_lines }}"
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the Debian or Ubuntu server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists