- hosts: "*"
  tasks:
    - name: install cockpit and cockpit dependencies
      apt:
        name:
        - cockpit
        state: present
        update_cache: true
    - name: install 45drives cockpit navigator plugin
      apt:
        deb: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        state: present
      register: apt_output
    - name: install 45drives cockpit file sharing plugin
      apt:
        deb: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.2/cockpit-file-sharing_3.3.2-1focal_all.deb
        state: present
      register: apt_output
    - name: Enable service cockpit and ensure it is not masked
      systemd:
        name: cockpit
        enabled: yes
        masked: no
    - name: Start cockpit service if it isn't already
      systemd:
        state: started
        name: cockpit
    - name: check cockpit status
      command: systemctl status "{{ item }}"
      with_items:
      - cockpit
      register: result
      ignore_errors: yes
    - name: report
      debug:
        var: result
        
