- hosts: "*"
  become: true
  tasks:
    - name: Preliminary checks
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: Install all updates
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: Install QEMU guest agent and cockpit
      apt:
        name:
        - qemu-guest-agent
        - cockpit
        - cifs-utils
        - keyutils
        state: present
        update_cache: true
    - name: Install 45drives cockpit navigator plugin
      apt:
        deb: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        state: present
    - name: Install 45drives cockpit file sharing plugin
      apt:
        deb: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.2/cockpit-file-sharing_3.3.2-1focal_all.deb
        state: present
    - name: start guest agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    - name: Enable and start service cockpit and ensure it is not masked
      systemd:
        name: cockpit
        enabled: yes
        state: started
        masked: no
    - name: Check that NAS-01 mount point exists
      ansible.builtin.file:
        path: /nas-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett
    - name: Mount NAS-01 network share
      ansible.posix.mount:
        src: //NAS-01.homelab.internal/Media
        path: /nas-01
        fstype: cifs
        opts: 'uid=abeckett,mfsymlinks,username=abeckett-local,password=Chocolate-1245!'
        state: mounted
    - name: Check that STORAGE-01 mount point exists
      ansible.builtin.file:
        path: /storage-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett
    - name: Mount STORAGE-01 network share
      ansible.posix.mount:
        src: //PHS-STR-01.homelab.internal/Media
        path: /storage-01
        fstype: cifs
        opts: 'uid=abeckett,mfsymlinks,username=abeckett,password=Chocolate-1245!'
        state: mounted
