- hosts: "*"
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: install qemu guest agent
      apt:
        name:
        - qemu-guest-agent
        state: present
        update_cache: true
    - name: start guest agent service
      systemd:
        state: started
        name: qemu-guest-agent        
