- hosts: "*"
  become: true
  tasks:
    - name: Preliminary checks # checks that apt lists directory exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755

    - name: Install all updates # updates cache and upgrades all packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        
    - name: Install required base-packages (qemu-guest-agent, cockpit, cifs-utils) # installs qemu guest agent, cockpit, cifs-utils for cifs support and keyutils
      apt:
        name:
        - qemu-guest-agent
        - cockpit
        - cifs-utils
        - keyutils
        state: present

    - name: Install cockpit navigator plugin
      apt:
        deb: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        state: present

    - name: Install cockpit file sharing plugin
      apt:
        deb: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.2/cockpit-file-sharing_3.3.2-1focal_all.deb
        state: present

    - name: Start all newly installed services
      systemd:
        name: 
        - qemu-guest-agent
        - cockpit
        enabled: yes
        state: started
        masked: no

    - name: Check that NAS-01 mount point exists
      ansible.builtin.file:
        path: /nas-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett

    - name: Mount NAS-01 network share
      ansible.posix.mount:
        src: //NAS-01.homelab.internal/Media
        path: /nas-01
        fstype: cifs
        opts: "{{ nas_01 }}"
        state: mounted

    - name: Check that STORAGE-01 mount point exists
      ansible.builtin.file:
        path: /storage-01
        state: directory
        mode: '0755'
        owner: abeckett
        group: abeckett

    - name: Mount STORAGE-01 network share
      ansible.posix.mount:
        src: //PHS-STR-01.homelab.internal/Media
        path: /storage-01
        fstype: cifs
        opts: "{{ storage_01 }}"
        state: mounted
