- hosts: "*"
  become: true
  tasks:
    - name: Get OS release codename
      command: lsb_release -cs
      register: release_codename
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Docker APT Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_codename.stdout }} stable
        state: present
    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
    - name: Start and enable Docker systemd service.
      systemd:
        name: docker
        state: started
        enabled: true
        daemon_reload: true