- name: Security update report and Discord notification
  hosts: virtual_infrastructure
  roles:
    - update-report-aggregated-alert
  vars:
    update_report_discord_webhook_url: "{{ lookup('env', 'VMS_LXCS_UPDATE_REPORT_DISCORD_WEBHOOK_URL') }}"
