- name: Security update report and Discord notification
  hosts: physical_hosts
  roles:
    - update-report-single-alert
  vars:
    update_report_discord_webhook_url: "{{ lookup('env', 'PHYSICAL_HOSTS_UPDATE_REPORT_DISCORD_WEBHOOK_URL') }}"
