- name: Security update report and Discord notification
  hosts: proxmox_clusters
  roles:
    - update-report-single-alert
  vars:
    update_report_discord_webhook_url: "{{ lookup('env', 'PVE_CLUSTERS_UPDATE_REPORT_DISCORD_WEBHOOK_URL') }}"
