- name: Security update report and Discord notification
  hosts: proxmox_clusters
  roles:
    - update-report-single-alert
  vars:
    update_report_bot_reports_url: "{{ lookup('env', 'BOT_URL') }}"
    update_report_bot_reports_token: "{{ lookup('env', 'BOT_TOKEN') }}"
    update_report_scope: "pve_clusters"
    update_report_title: "PVE Clusters Update Report"
