- name: Security update report and Discord notification
  hosts: physical_hosts
  roles:
    - update-report-single-alert
  vars:
    update_report_bot_reports_url: "{{ lookup('env', 'BOT_URL') }}"
    update_report_bot_reports_token: "{{ lookup('env', 'BOT_TOKEN') }}"
    update_report_scope: "physical_hosts"
    update_report_title: "Physical Hosts Update Report"
