- name: Security update report and Discord notification
  hosts: virtual_infrastructure
  roles:
    - update-report-aggregated-alert
  vars:
    update_report_bot_reports_url: "{{ lookup('env', 'BOT_URL') }}"
    update_report_bot_reports_token: "{{ lookup('env', 'BOT_TOKEN') }}"
    update_report_scope: "vms_lxcs"
    update_report_title: "VMS/LXCS Update Report"
