- name: Clone virtual-machine template to new VM
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: 127.0.0.1
    clone: template
    vmid: "{{ template_id }}"
    name: "{{ vm_name }}"
    newid: "{{ vm_id }}"
    storage: pool-1 
    format: raw
    timeout: 120
  async: 120
  poll: 5
- name: Edit cloned virtual-machine with new cloud-init parameters
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: 127.0.0.1
    name: "{{ vm_name }}"
    tags: "{{ tags }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    citype: nocloud
    ciuser: "{{ username }}"
    cipassword: "{{ password }}"
    sshkeys: "{{ sshkeys }}"
    searchdomains: 'homelab.internal'
    nameservers: 192.168.0.210
    ipconfig: 
      ipconfig0: "{{ ip_address }}"
    update: true
  async: 60
  poll: 5
- name: Re-size cloned virtual-machine disk
  community.general.proxmox_disk:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: 127.0.0.1
    name: "{{ vm_name }}"
    disk: scsi0
    size: "{{ disk_size }}"
    state: resized
  async: 60
  poll: 5
- name: Start cloned virtual-machine
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: 127.0.0.1
    name: "{{ vm_name }}"
    state: started
  async: 60
  poll: 5
