- name: Clone virtual-machine template to new VM
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    clone: template
    vmid: "{{ template_id }}"
    name: "{{ vm_name }}"
    newid: "{{ vm_id }}"
    storage: pool-1 
    format: raw
    timeout: 300
- name: Edit cloned virtual-machine with new cloud-init parameters
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    name: "{{ vm_name }}"
    tags: "{{ tags }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    citype: nocloud
    ciuser: "{{ username }}"
    cipassword: "{{ password }}"
    sshkeys: "{{ sshkeys }}"
    searchdomains: 'homelab.internal'
    nameservers: 192.168.0.210
    ipconfig: 
      ipconfig0: "{{ ip_address }}"
    update: true
    timeout: 300
- name: Re-size cloned virtual-machine disk
  community.general.proxmox_disk:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    name: "{{ vm_name }}"
    disk: scsi0
    size: "{{ disk_size }}"
    state: resized
    timeout: 300
- name: Start cloned virtual-machine
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    name: "{{ vm_name }}"
    state: started
    timeout: 300
- name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30