- name: Create directory for docker compose files
  ansible.builtin.file:
    path: /mnt/gluster/containers/compose
    state: directory
    mode: '777'
- name: Create directory for traefik compose files
  ansible.builtin.file:
    path: /mnt/gluster/containers/compose/traefik
    state: directory
    mode: '777'
- name: Create directory for traefik container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/traefik
    state: directory
    mode: '777'
- name: Create directory for traefik letsencrypt container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/traefik/letsencrypt
    state: directory
    mode: '777'
- name: Download Traefik static configuration file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Traefik-Configuration/main/traefik.yml
    dest: /mnt/gluster/containers/traefik/traefik.yml
    mode: '777'
- name: Download Traefik dynamic configuration file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Traefik-Configuration/main/fileConfig.yml
    dest: /mnt/gluster/containers/traefik/fileConfig.yml
    mode: '777'
- name: Download Traefik compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/traefik.yaml
    dest: /mnt/gluster/containers/compose/traefik/traefik.yaml
    mode: '777'
- name: Create the proxy network
  community.docker.docker_network:
    name: proxy
    state: present
    scope: swarm
    driver: bridge
- name: Deploy Traefik from the compose file
  community.docker.docker_stack:
    state: present
    name: traefik
    compose:
      - /mnt/gluster/containers/compose/traefik/traefik.yaml
- name: Create directory for authentik compose files
  ansible.builtin.file:
    path: /mnt/gluster/containers/compose/authentik
    state: directory
    mode: '777'
- name: Copy environment variables for Authentik
  ansible.builtin.copy:
    src: /home/abeckett/authentik.env
    dest: /mnt/gluster/containers/compose/authentik/.env
    mode: '777'
- name: Download Authentik compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/authentik.yaml
    dest: /mnt/gluster/containers/compose/authentik/authentik.yaml
    mode: '777'
- name: Create directory for Authentik container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/authentik
    state: directory
    mode: '777'
- name: Create directory for Authentik container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/authentik/media
    state: directory
    mode: '777'
- name: Create directory for Authentik container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/authentik/certs
    state: directory
    mode: '777'
- name: Create directory for Authentik container configs
  ansible.builtin.file:
    path: /mnt/gluster/containers/authentik/custom-templates
    state: directory
    mode: '777'
- name: Create the proxy network
  community.docker.docker_network:
    name: authentik-network
    state: present
    scope: swarm
- name: Deploy Authentik from the compose file
  community.docker.docker_stack:
    state: present
    name: authentik
    compose:
      - /mnt/gluster/containers/compose/authentik/authentik.yaml
