- name: Start portainer_agent service
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:2.18.4
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
