- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: Create Docker GPG keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download and add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  become: yes
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: yes

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  become: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Start Portainer-Agent service
  community.docker.docker_container:
    name: Portainer-Agent
    image: portainer/agent:2.27.9
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

- name: Create Pelican directory
  file:
    path: /opt/pelican
    state: directory
    owner: root
    group: root
    mode: '0777'
    recurse: yes
  become: yes

- name: Create Pelican logs directory
  file:
    path: /var/www/pelican/storage/logs
    state: directory
    owner: root
    group: root
    mode: '0777'
    recurse: yes
  become: yes

- name: Create Pelican public directory
  file:
    path: /var/www/pelican/public
    state: directory
    owner: root
    group: root
    mode: '0777'
    recurse: yes
  become: yes

- name: Download HyveCloud logo
  get_url:
    url: https://auth.hyvecloud.dev/media/public/icons/HyveCloudClearBlackCropped.png
    dest: /var/www/pelican/public/HyveCloudClearBlackCropped.png
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Create Caddy directory
  file:
    path: /etc/caddy/
    state: directory
    owner: root
    group: root
    mode: '0777'
    recurse: yes
  become: yes

- name: Create Caddyfile configuration
  copy:
    content: |
      {
        admin off
        servers {
            trusted_proxies static {{ reverse_proxy_ip }}
        }
      }

      :80 {
        root * /var/www/html/public
        encode gzip

        php_fastcgi 127.0.0.1:9000
        file_server
      }
    dest: /etc/caddy/Caddyfile
    owner: root
    mode: '0644'
  become: yes