- name: Download the Webmin repos setup script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
    dest: /setup-repos.sh
    mode: '0777'
- name: Execute the script
  ansible.builtin.command: sh /setup-repos.sh
- name: Install Webmin and prerequisites
  ansible.builtin.apt:
    update_cache: true
    name: webmin
    state: present
    install_recommends: true
