- name: Preliminary checks [Linux - Debian]
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: "0755"
  when: ansible_facts.os_family == "Debian"

- name: Enable Backports repository on Ubuntu Jammy Machines [Linux]
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '22.04'

- name: Install all updates [Linux - Debian]
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true
  when: ansible_facts.os_family == "Debian"

- name: Install all updates [Linux - RedHat/CentOS/Alma/Rocky]
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Install all critical and security updates [Windows]
  ansible.windows.win_updates:
    category_names:
      - Critical Updates
      - Security Updates
      - Updates
      - Definition Updates
    state: installed
  register: win_update_result
  when: ansible_facts.os_family == "Windows"

- name: Reboot if required when windows updates stuck waiting on reboot before the rest will install [Windows]
  ansible.windows.win_reboot:
    msg: "Rebooting to complete updates"
    pre_reboot_delay: 30
    post_reboot_delay: 60
  when:
    - ansible_facts.os_family == "Windows"
    - win_update_result.reboot_required | default(false)

- name: Run Windows update check & install again after reboot [Windows]
  ansible.windows.win_updates:
    category_names:
      - Critical Updates
      - Security Updates
      - Updates
      - Definition Updates
    state: installed
  when:
    - ansible_facts.os_family == "Windows"
    - win_update_result.reboot_required | default(false)
