- name: Preliminary checks [Linux]
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755
  when:
    - ansible_facts.os_family == "Debian"
- name: Install all updates [Linux]
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes
  when:
    - ansible_facts.os_family == "Debian"
- name: Install all critical and security updates [Windows]
  win_updates:
    category_names:
    - CriticalUpdates
    - SecurityUpdates
    state: installed
  when:
    - ansible_facts.os_family == "Windows"
