- name: Preliminary checks [Linux]
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: "0755"
  when:
    - ansible_facts.os_family == "Debian"
- name: Install all updates [Linux]
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true
  when:
    - ansible_facts.os_family == "Debian"
- name: Install all critical and security updates [Windows]
  ansible.windows.win_updates:
    category_names:
      - CriticalUpdates
      - SecurityUpdates
    state: installed
  when:
    - ansible_facts.os_family == "Windows"
