- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /get_helm.sh
    mode: '0700'
- name: Run the Helm install script
  ansible.builtin.shell: /get_helm.sh
- name: Create a namespace for Rancher
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present
- name: Add the Rancher-Latest helm repository
  ansible.builtin.command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

