- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /get_helm.sh
    mode: '0700'
- name: Run the Helm install script
  ansible.builtin.shell: /get_helm.sh
- name: Add the Rancher-Latest Helm repository
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"
- name: Add the Jetstack Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
- name: Update Cert-Manager version
  ansible.builtin.command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.crds.yaml
- name: Deploy the Cert-Manager Helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
- name: Deploy the Rancher Helm Chart
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    create_namespace: true
    set_values:
      - value: hostname=VM-K3S-SERVER-01.hyvecloud.local
        value_type: string
      - value: bootstrapPassword="{{ rancher_password }}"
        value_type: string

