- name: Reboot systems [Linux]
  ansible.builtin.reboot:
    post_reboot_delay: 60
    test_command: uptime
  when:
    - ansible_facts.os_family == "Debian"
- name: Reboot systems [Windows]
  ansible.windows.win_reboot:
    post_reboot_delay: 60
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  when:
    - ansible_facts.os_family == "Windows"