- name: Take a snapshot of the virtual machine
  community.general.proxmox_snap:
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    snapname: "{{ snapshot_name }}"
    state: present
