- name: Create mountpoint for Gluster volume
  ansible.builtin.file:
    path: /mnt/gluster
    state: directory
    owner: abeckett
    mode: '777'
- name: Mount Gluster volume
  ansible.posix.mount:
    src: "{{ ansible_host }}:/gv0"
    path: /mnt/gluster
    fstype: glusterfs
    state: mounted
    opts: rw
- name: Create directory for mount service override
  ansible.builtin.file:
    path: /etc/systemd/system/srv.mount.d/
    state: directory
    owner: abeckett
    mode: '777'
- name: Create override file for systemd-mount that delays mounting until after glusterfs-server.service has started
  ansible.builtin.copy:
    dest: /etc/systemd/system/srv.mount.d/override.conf
    mode: '777'
    owner: abeckett
    content: |
      [Unit]
      After=glusterfs-server.service
      Wants=glusterfs-server.service
