- name: Create mountpoint for Gluster volume
  ansible.builtin.file:
    path: /mnt/gluster
    state: directory
- name: Mount Gluster volume
  ansible.posix.mount:
    src: "{{ ansible_host }}:/gv0"
    path: /mnt/gluster
    fstype: glusterfs
    state: mounted
    opts: rw
