- name: Take a snapshot of the virtual machine with early configuration before role setup
  community.general.proxmox_snap:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    vmid: "{{ vm_id }}"
    snapname: Post-update-early-configuration
    state: present