- name: Stop Virtual Machine
  community.general.proxmox_kvm:
    node: phs-hv-01
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: phs-hv-01
    name: VM-LB-01
    state: stopped
    force: true
    timeout: 300