- name: Send notification message via Mattermost
  mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_webhook_key }}"
    text: |
          #### Playbook Deployment Alert
          | **Playbook**              | **Host**                     | **Status**                                                                                   |
          |---------------------------|------------------------------|----------------------------------------------------------------------------------------------|
          | *{{ ansible_play_name }}* | **{{ inventory_hostname }}** | ![Mattermost](https://cdn-icons-png.flaticon.com/512/3541/3541892.png =40 "Mattermost Icon") |