- name: Start Virtual Machine
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    state: started
    force: true
    timeout: 300
