- name: Start Virtual Machine
  community.general.proxmox_kvm:
    node: "{{ proxmox_node }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    api_host: "{{ proxmox_node }}"
    name: "{{ vm_name }}"
    state: started
    force: true
    timeout: 300
