- name: Reboot the Proxmox Node
  ansible.builtin.reboot:
    reboot_timeout: 900

- name: Wait for Proxmox Node to be reachable after reboot
  ansible.builtin.wait_for_connection:
    timeout: 600
