- name: Start glusterfs/glusterd service and create directory for brick
  hosts: swarm_vms
  become: true
  tasks:
    - name: Start glusterd service
      systemd:
        name: glusterd
        enabled: yes
        state: started
    - name: Create GlusterFS brick-1 directory
      ansible.builtin.file:
        path: /glusterfs/bricks/gv0
        state: directory
- name: Create mountpoint and glusterFS volume and initialize
  hosts: loadbalancer
  become: true
  tasks:
    - name: Create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - VM-SWARM-01.homelab.internal
          - VM-SWARM-02.homelab.internal
          - VM-SWARM-03.homelab.internal
    - name: Create GlusterFS volume
      gluster.gluster.gluster_volume:
        state: present
        name: gv0
        replicas: 4
        bricks: /glusterfs/bricks/gv0
        cluster:
          - VM-LB-01
          - VM-SWARM-01.homelab.internal
          - VM-SWARM-02.homelab.internal
          - VM-SWARM-03.homelab.internal
        force: true
      run_once: true
    - name: Start GlusterFS volume
      gluster.gluster.gluster_volume:
        state: started
        name: gv0
- name: Create mountpoint and mount glusterFS volume
  hosts: loadbalancer,swarm_manager,swarm_nodes
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: "{{ ansible_host }}:/gv0"
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted