- name: Start glusterfs/glusterd and create directory for brick
  hosts: glusterfs_servers                                          # Your inventory file should contain 3 host groups
  become: true                                                      # [glusterfs_servers] containing all machines running glusterfs
  tasks:                                                            # [glusterfs_primary_node] which will be used to initialize the gluster filesystem
    - name: Start glusterd service                                  # [glusterfs_connected_nodes] which are the nodes which will connect to the primary
      systemd:
        name: glusterd
        enabled: yes
        state: started
    - name: Create GlusterFS brick-1 directory
      ansible.builtin.file:
        path: /glusterfs/bricks/gv0
        state: directory
- name: Create mountpoint and glusterfs volume, and mount to primary node
  hosts: glusterfs_primary_node
  become: true
  tasks:
    - name: Create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - VM-SWARM-01.homelab.internal
          - VM-SWARM-02.homelab.internal
          - VM-SWARM-03.homelab.internal
    - name: Create GlusterFS volume
      gluster.gluster.gluster_volume:
        state: present
        name: gv0
        replicas: 4                                                 # Change this depending on the number of servers in the cluster
        bricks: /glusterfs/bricks/gv0
        cluster:
          - VM-LB-01
          - VM-SWARM-01.homelab.internal
          - VM-SWARM-02.homelab.internal
          - VM-SWARM-03.homelab.internal
        force: true
      run_once: true
    - name: Start GlusterFS volume
      gluster.gluster.gluster_volume:
        state: started
        name: gv0
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: "{{ ansible_host }}:/gv0"
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted
- name: Create mountpoint and mount glusterfs volume on connected nodes
  hosts: glusterfs_connected_nodes
  become: true
  tasks:
    - name: Create mountpoint for Gluster volume
      ansible.builtin.file:
        path: /mnt/gluster
        state: directory
    - name: Mount Gluster volume
      ansible.posix.mount:
        src: "{{ ansible_host }}:/gv0"
        path: /mnt/gluster
        fstype: glusterfs
        state: mounted