- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ nodes }}"
- name: Create GlusterFS volume
  gluster.gluster.gluster_volume:
    state: present
    name: gv0
    replicas: "{{ replicas }}"
    bricks: /glusterfs/bricks/gv0
    cluster: "{{ cluster }}"
    force: true
  run_once: true
- name: Start GlusterFS volume
  gluster.gluster.gluster_volume:
    state: started
    name: gv0