- name: Deploy docker containers for portainer, NGINX and file manager on the loadbalancer node
  hosts: '*'
  become: true
  tasks:
    - name: Spin-up a Portainer instance for management of Swarm
      docker_container:
        name: Portainer
        image: portainer/portainer-ce
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9000:9000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
    - name: Deploy NGINX load-balancer
      community.docker.docker_container:
        name: Load-Balancer
        image: nginx
        state: started
        volumes:
          - /nas-01/Container-configs/loadbalancer/:/etc/nginx/conf.d
        ports:
        - 9003-9020:9003-9020
        - 10000-10020:10000-10020
        - 11000-11020:11000-11020
        - 12000-12020:12000-12020
        - 13000-13020:13000-13020
        - 14000-14020:14000-14020
        - 15000-15020:15000-15020
        restart_policy: always
    - name: Deploy File-Manager for GlusterFS volume
      community.docker.docker_container:
        name: File-Manager
        image: hurlenko/filebrowser
        state: started
        volumes:
          - /nas-01/Container-configs/file-browser-glusterfs:/config
          - /mnt/gluster:/data
        ports:
          - 9002:8080
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        restart_policy: always