- name: Install all critical and security updates [Windows]
  ansible.windows.win_updates:
    category_names:
      - CriticalUpdates
      - SecurityUpdates
    state: installed
  when:
    - ansible_facts.os_family == "Windows"
  register: result
  notify:
    - Send success notification message via Mattermost
    - Send failure notification message via Mattermost