- name: Clone template to VM-LB-01
 community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-LB-01
		newid: 200
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-SWARM-01
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-SWARM-01
		newid: 201
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-SWARM-02
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-SWARM-02
		newid: 202
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-SWARM-03
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-SWARM-03
		newid: 203
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-GIT-01
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-GIT-01
		newid: 204
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-K3S-01-MASTER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-K3S-01-MASTER
		newid: 205
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-K3S-02-WORKER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-K3S-02-WORKER
		newid: 206
		storage: pool-1
		format: raw
		timeout: 300
- name: Clone template to VM-K3S-03-WORKER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		clone: template
		vmid: 1000
		name: VM-K3S-03-WORKER
		newid: 207
		storage: pool-1
		format: raw
		timeout: 300
- name: Edit VM-LB-01 with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-LB-01
		tags: load-balancer,docker,glusterfs
		cores: 4
		memory: 2048
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.160/24
		update: true
		timeout: 300
- name: Edit VM-SWARM-01 with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-01
		tags: docker,app-server,glusterfs
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.161/24
		update: true
		timeout: 300
- name: Edit VM-SWARM-02 with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-02
		tags: docker,app-server,glusterfs
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.162/24
		update: true
		timeout: 300
- name: Edit VM-SWARM-03 with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-03
		tags: docker,app-server,glusterfs
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.163/24
		update: true
		timeout: 300
- name: Edit VM-GIT-01 with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-GIT-01
		tags: gitlab,app-server
		cores: 4
		memory: 2048
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.164/24
		update: true
		timeout: 300
- name: Edit VM-K3S-01-MASTER with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-01-MASTER
		tags: kubernetes,app-server,master
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.165/24
		update: true
		timeout: 300
- name: Edit VM-K3S-02-WORKER with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-02-WORKER
		tags: kubernetes,app-server,worker
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.166/24
		update: true
		timeout: 300
- name: Edit VM-K3S-03-WORKER with new cloud-init parameters
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-03-WORKER
		tags: kubernetes,app-server,worker
		cores: 4
		memory: 4096
		citype: nocloud
		ciuser: "{{ username }}"
		cipassword: "{{ password }}"
		sshkeys: "{{ sshkeys }}"
		searchdomains: 'homelab.internal'
		nameservers: 192.168.0.210
		ipconfig: 
			ipconfig0: gw=192.168.0.1,ip=192.168.0.167/24
		update: true
		timeout: 300
- name: Re-size VM-LB-01 disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-LB-01
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-SWARM-01 disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-01
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-SWARM-02 disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-02
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-SWARM-03 disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-03
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-GIT-01 disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-GIT-01
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-K3S-01-MASTER disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-01-MASTER
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-K3S-02-WORKER disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-02-WORKER
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Re-size VM-K3S-03-WORKER disk
	community.general.proxmox_disk:
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-03-WORKER
		disk: scsi0
		size: 50G
		state: resized
		timeout: 300
- name: Start VM-LB-01
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-LB-01
		state: started
		timeout: 300
- name: Start VM-SWARM-01
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-01
		state: started
		timeout: 300
- name: Start VM-SWARM-02
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-02
		state: started
		timeout: 300
- name: Start VM-SWARM-03
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-SWARM-03
		state: started
		timeout: 300
- name: Start VM-GIT-01
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-GIT-01
		state: started
		timeout: 300
- name: Start VM-K3S-01-MASTER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-01-MASTER
		state: started
		timeout: 300
- name: Start VM-K3S-02-WORKER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-02-WORKER
		state: started
		timeout: 300
- name: Start VM-K3S-03-WORKER
	community.general.proxmox_kvm:
		node: phs-hv-01
		api_user: "{{ proxmox_user }}"
		api_password: "{{ proxmox_password }}"
		api_host: phs-hv-01
		name: VM-K3S-03-WORKER
		state: started
		timeout: 300
- name: Pause for 5 minutes
	ansible.builtin.pause:
		seconds: 300