- name: Check if Swarm has already been Initialized
  ansible.builtin.command: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: false
- name: Initialize Docker Swarm
  ansible.docker.docker_swarm:
    state: present
  when: swarm_status.rc != 0
  run_once: true
- name: Change task-history limit to 0
  ansible.builtin.command: docker swarm update --task-history-limit 0
  changed_when: false
- name: Get the worker join-token
  ansible.builtin.command: docker swarm join-token --quiet worker
  register: worker_token
  changed_when: false
