- name: Install required packages
  ansible.builtin.apt:
    name:
      - cifs-utils
      - nfs-common
      - keyutils
    state: present
- name: Create NAS-01 local directory
  ansible.builtin.file:
    path: /nas-01
    state: directory
    mode: '777'
- name: Mount NAS-01 network share
  ansible.posix.mount:
    src: NAS-01.homelab.internal:/volume1/Media
    path: /nas-01
    fstype: nfs
    boot: true
    opts: rw,sync,hard
    state: mounted
- name: Create STORAGE-01 local directory
  ansible.builtin.file:
    path: /storage-01
    state: directory
    mode: '777'
- name: Mount STORAGE-01 network share
  ansible.posix.mount:
    src: STORAGE-01.homelab.internal:/mnt/user/media
    path: /storage-01
    fstype: nfs
    boot: true
    opts: rw,sync,hard
    state: mounted
