- name: Install required packages
  ansible.builtin.apt:
    name:
      - cifs-utils
      - nfs-common
      - keyutils
    state: present
- name: Create NAS-01 local directory
  ansible.builtin.file:
    path: /mnt/nas-01
    state: directory
    mode: '777'
- name: Mount NAS-01 network share
  ansible.posix.mount:
    src: NAS-01.hyvecloud.internal:/volume1/Media
    path: /mnt/nas-01
    fstype: nfs
    boot: true
    opts: rw,sync,hard
    state: mounted
