- name: Send notification message via Mattermost
  mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_webhook_key }}"
    text: '**[*{{ ansible_play_name }}*] playbook has been deployed on {{ inventory_hostname }}**'