- name: Add /var/lib/pufferpanel/ directory
  ansible.builtin.file:
    path: /var/lib/pufferpanel/
    state: directory
- name: Add /var/www/pufferpanel/ directory
  ansible.builtin.file:
    path: /var/www/pufferpanel/
    state: directory
- name: Add /home/abeckett/config/pufferpanel/ directory
  ansible.builtin.file:
    path: /home/abeckett/config/pufferpanel/
    state: directory
- name: Deploy Pufferpanel docker container
  docker_container:
    name: PufferPanel
    image: pufferpanel/pufferpanel:latest
    state: started
    recreate: yes
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "5657:5657"
    volumes:
      - /home/abeckett/config/pufferpanel/config:/etc/pufferpanel
      - /var/lib/pufferpanel:/var/lib/pufferpanel
      - /var/www/pufferpanel/:/var/www/pufferpanel/
      - /var/run/docker.sock:/var/run/docker.sock
- name: Run docker exec command to add the pufferpanel user within the container
  shell: |
        docker exec -it pufferpanel /pufferpanel/pufferpanel user add