- name: Create directory for container configuration
  ansible.builtin.file:
    path: "/mnt/gluster/containers/{{ service }}"
    state: directory
    owner: abeckett
    mode: '777'
- name: Download container compose file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/{{ service }}.yaml"
    dest: "/mnt/gluster/{{ service }}.yaml"
    owner: abeckett
    mode: '777'
- name: Deploy container from the compose file
  community.docker.docker_stack:
    state: present
    name: "{{ service }}"
    compose:
      - "/mnt/gluster/{{ service }}.yaml"
- name: Delete compose file after stack deployment
  ansible.builtin.file:
    path: "/mnt/gluster/{{ service }}.yaml"
    state: absent
