- name: Check if Swarm is Already Initialized
  ansible.builtin.command: docker node ls
  register: swarm_status
  ignore_errors: true
  changed_when: false
  tags: swarm

- name: Add Managers to the Swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars['swarm_01']['manager_token']['stdout'] }}"
    remote_addrs: |
      - "{{ hostvars['swarm_01']['ansible_default_ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0
  tags: swarm
