- name: Send notification message via Mattermost
  mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_webhook_key }}"
    text: |
          #### Playbook Deployment Alert
          | **Playbook**              | **Host**                     | **Status**                                                                                                        |
          |---------------------------|------------------------------|-------------------------------------------------------------------------------------------------------------------|
          | *{{ ansible_play_name }}* | **{{ inventory_hostname }}** | ![Mattermost](https://static-00.iconduck.com/assets.00/failure-icon-1024x1024-lpdgzomh.png =40 "Mattermost Icon") |