- name: Install required packages
  apt:
    name:
    - glusterfs-server
    - glusterfs-client
    state: present
- name: Start glusterd service
  systemd:
    name: glusterd
    enabled: yes
    state: started
- name: Create GlusterFS brick-1 directory
  ansible.builtin.file:
    path: /glusterfs/bricks/gv0
    state: directory
