- name: Install required packages [Debian/Ubuntu]
  apt:
    name:
    - glusterfs-server
    - glusterfs-client
    state: present
  when:
    - ansible_facts.os_family == "Debian"
- name: Install required base-packages [CentOS/Rocky]
  dnf:
    name: 
    - glusterfs-server
    - glusterfs-client
    state: present
  when:
    - ansible_facts.os_family == "RedHat"
- name: Start glusterd service
  systemd:
    name: glusterd
    enabled: yes
    state: started
- name: Create GlusterFS brick-1 directory
  ansible.builtin.file:
    path: /glusterfs/bricks/gv0
    state: directory
