- name: Download OpenBytes GPG key
  get_url:
    url: https://repo.openbytes.ie/openbytes.gpg
    dest: /usr/share/keyrings/openbytes.gpg
    mode: '0644'
- name: Add Patchman repository
  copy:
    dest: /etc/apt/sources.list.d/patchman.list
    content: "deb [signed-by=/usr/share/keyrings/openbytes.gpg] https://repo.openbytes.ie/patchman/debian bookworm main"
    mode: '0644'
- name: Update APT package cache
  apt:
    update_cache: yes
- name: Install Patchman Client
  apt:
    name: patchman-client
    state: present
- name: Update Patchman Client configuration
  replace:
    path: /etc/patchman/patchman-client.conf
    regexp: 'https://patchman.example.com'
    replace: 'http://192.168.10.151/patchman/'
- name: Create cronjob for Patchman Client
  cron:
    name: "Run Patchman Client daily"
    minute: "0"
    hour: "1"
    job: "/usr/bin/patchman-client"
- name: Run Patchman Client
  command: /usr/bin/patchman-client