- name: Download Portainer Agent Stack compose file
  ansible.builtin.get_url:
    url: https://downloads.portainer.io/ce2-18/portainer-agent-stack.yml
    dest: /mnt/gluster/containers/portainer/portainer-agent-stack.yml
- name: Deploy Portainer Agent Stack from the compose file
  docker_stack:
    state: present
    name: portainer
    compose:
      - /mnt/gluster/containers/portainer/portainer-agent-stack.yml
- name: Deploy File-Manager for GlusterFS volume
  docker_swarm_service:
    name: File-Manager
    image: hurlenko/filebrowser
    state: present
    volumes:
      - type: bind
        source: /mnt/gluster/containers/file-browser
        target: /config
      - type: bind
        source: /mnt/gluster
        target: /data
    publish:
      - target_port: 8080
        published_port: 9001
        protocol: tcp
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
    restart_config:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
- name: Deploy VSCode for Swarm Container config editing
  docker_swarm_service:
    name: VSCode-Server
    image: lscr.io/linuxserver/code-server
    state: present
    volumes:
      - type: bind
        source: /mnt/gluster/containers/vscode-server
        target: /config
      - type: bind
        source: /mnt/gluster/containers
        target: /containers
    publish:
      - target_port: 8443
        published_port: 9002
        protocol: tcp
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      DEFAULT_WORKSPACE: "/home-assistant"
    restart_config:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s