- name: Create directory for docker compose files
  ansible.builtin.file:
    path: /mnt/gluster/containers/compose
    state: directory

- name: Create directory for portainer configuration
  ansible.builtin.file:
    path: /mnt/gluster/containers/portainer
    state: directory

- name: Download Portainer Agent Stack compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/utilities/portainer.yaml
    dest: /mnt/gluster/containers/compose/portainer.yaml

- name: Deploy Portainer Agent Stack from the compose file
  docker_stack:
    state: present
    name: portainer
    compose:
      - /mnt/gluster/containers/compose/portainer.yaml

- name: Create directory for file-browser configuration
  ansible.builtin.file:
    path: /mnt/gluster/containers/file-browser
    state: directory

- name: Download File-Manager compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/utilities/filebrowser.yaml
    dest: /mnt/gluster/containers/compose/filebrowser.yaml

- name: Deploy File-Manager for GlusterFS volume
  docker_stack:
    state: present
    name: file-browser
    compose:
      - /mnt/gluster/containers/compose/filebrowser.yaml

- name: Create directory for vscode-server configuration
  ansible.builtin.file:
    path: /mnt/gluster/containers/vscode-server
    state: directory

- name: Download VSCode-Server compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/utilities/vscode-server.yaml
    dest: /mnt/gluster/containers/compose/vscode-server.yaml

- name: Deploy File-Manager for GlusterFS volume
  docker_stack:
    state: present
    name: vscode-server
    compose:
      - /mnt/gluster/containers/compose/vscode-server.yaml

- name: Download Shepherd compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/utilities/shepherd.yaml
    dest: /mnt/gluster/containers/compose/shepherd.yaml

- name: Deploy File-Manager for GlusterFS volume
  docker_stack:
    state: present
    name: shepherd
    compose:
      - /mnt/gluster/containers/compose/shepherd.yaml
