- name: Spin-up a Portainer instance for management of Swarm
  docker_container:
    name: Portainer
    image: portainer/portainer-ce
    state: started
    recreate: yes
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
- name: Deploy File-Manager for GlusterFS volume
  community.docker.docker_container:
    name: File-Manager
    image: hurlenko/filebrowser
    state: started
    volumes:
      - /mnt/gluster/containers/file-browser:/config
      - /mnt/gluster:/data
    ports:
      - 9002:8080
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
    restart_policy: always
