- name: Install qemu-guest-agent service for proper compatibility with proxmox hypervisor
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    state: present
    update_cache: yes
- name: Start qemu-guest-agent service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started