- name: Create directory for container configuration
  ansible.builtin.file:
    path: "/mnt/gluster/containers/nginx"
    state: directory
    owner: abeckett
    mode: '777'
- name: Configure nginx to loadbalance connections to swarm
  ansible.builtin.copy:
    src: /home/abeckett/default.conf
    dest: /mnt/gluster/containers/nginx/default.conf
    mode: '777'
    owner: abeckett
- name: Download container compose file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/nginx.yaml"
    dest: "/mnt/gluster/nginx.yaml"
    owner: abeckett
    mode: '777'
- name: Deploy container from the compose file
  community.docker.docker_stack:
    state: present
    name: "nginx"
    compose:
      - "/mnt/gluster/nginx.yaml"
- name: Delete compose file after stack deployment
  ansible.builtin.file:
    path: "/mnt/gluster/nginx.yaml"
    state: absent
- name: Create directory for container configuration
  ansible.builtin.file:
    path: "/mnt/gluster/containers/nginx-proxy-manager"
    state: directory
    owner: abeckett
    mode: '777'
- name: Download container compose file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/nginx.yaml"
    dest: "/mnt/gluster/nginx-proxy-manager.yaml"
    owner: abeckett
    mode: '777'
- name: Deploy container from the compose file
  community.docker.docker_stack:
    state: present
    name: "nginx-proxy-manager"
    compose:
      - "/mnt/gluster/nginx-proxy-manager.yaml"
- name: Delete compose file after stack deployment
  ansible.builtin.file:
    path: "/mnt/gluster/nginx-proxy-manager.yaml"
    state: absent
- name: Create directory for container configuration
  ansible.builtin.file:
    path: "/mnt/gluster/containers/authentik"
    state: directory
    owner: abeckett
    mode: '777'
- name: Download container compose file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/adam-beckett-1999/Docker-Compose/main/nginx.yaml"
    dest: "/mnt/gluster/authentik.yaml"
    owner: abeckett
    mode: '777'
- name: Configure nginx to loadbalance connections to swarm
  ansible.builtin.copy:
    src: /home/abeckett/authentik.env
    dest: /mnt/gluster/.env
    mode: '777'
    owner: abeckett
- name: Deploy container from the compose file
  community.docker.docker_stack:
    state: present
    name: "authentik"
    compose:
      - "/mnt/gluster/authentik.yaml"
- name: Delete compose file after stack deployment
  ansible.builtin.file:
    path: "/mnt/gluster/authentik.yaml"
    state: absent