- name: Install required packages
  ansible.builtin.apt:
    name:
      - snmpd
      - snmp
      - libsnmp-dev
    state: present
- name: Install pysnmp for testing SNMP on hosts
  ansible.builtin.pip:
    name: pysnmp
- name: Configure SNMP
  ansible.builtin.copy:
    dest: /etc/snmp/snmpd.conf
    mode: '777'
    owner: abeckett
    content: |
      com2sec notConfigUser default HyveCloudHomelab

      group notConfigGroup v1 notConfigUser
      group notConfigGroup v2c notConfigUser

      view all included .1 80

      access notConfigGroup "" any noauth exact all none none
- name: Start and enable SNMPd systemd service.
  ansible.builtin.systemd:
    name: snmpd
    state: started
    enabled: true
    daemon_reload: true
- name: Restart SNMPd systemd service if already running.
  ansible.builtin.systemd:
    name: snmpd
    state: restarted
- name: Test that SNMP is working
  community.general.snmp_facts:
    host: '{{ inventory_hostname }}'
    version: v2c
    community: HyveCloudHomelab
  register: response
- name: Print the results of the test
  ansible.builtin.debug:
    var: response
