- name: Install required dependencies and base packages for every install
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-pip
      - virtualenv
      - python3
      - python3-setuptools
      - neofetch
    state: present
    update_cache: yes
