- name: Install required dependencies and base packages for every install
  ansible.builtin.apt:
    name:
      - software-properties-common
      - virtualenv
      - python3
      - python3-setuptools
      - python3-pip
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
