- name: Install required dependencies and base packages for every install
  ansible.builtin.apt:
    name: "{{ base_packages_common + base_packages_distro }}"
    state: present
    update_cache: true
  vars:
    base_packages_common:
      - virtualenv
      - python3
      - python3-pip
      - python3-setuptools
    base_packages_distro: >-
      {{
        ['software-properties-common']
        if ansible_facts['distribution'] == 'Ubuntu'
        else []
      }}
  when: ansible_facts['os_family'] == 'Debian'
