- name: Stop Virtual Machine
  community.general.proxmox_kvm:
    node: "HYPERVISOR-01"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "HYPERVISOR-01"
    vmid: "{{ vm_id }}"
    state: stopped
    force: true
    timeout: 300
