name: ansible-lint

on:
  push:
    branches: ["dev"]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible, ansible-lint, and required collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
          ansible-galaxy collection install community.general ansible.posix community.docker gluster.gluster ansible.windows
      - name: Run ansible-lint on playbooks and roles
        env:
          ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/collections:/usr/share/ansible/collections
        run: |
          ansible-lint *.yaml roles/*/tasks/*.yml